### ISSUE TITLE
AttributeError: 'MaskedConvolution2D' object has no attribute 'has_uninitialized_params'

### ISSUE THREAD

**Issue by PharrellWANG** [rampage644/wavenet#9]
Hi @rampage644, i am trying your pixelcnn implementation on cifar with `python train.py -g0 --levels 256 --out data/ --dataset cifar`, but I am receiving assertion error `AttributeError: 'MaskedConvolution2D' object has no attribute 'has_uninitialized_params'`. Why is it? I think I have all the dependencies installed.

**Comment by rampage644** [comment]
I think this is because some dependencies were updated (the code was developed almost 2 year ago). I didn't pin the version I've used as you can see.
Feel free to submit a fix.
